// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
 // 1. 文档侧边栏：只包含 guides 文件夹内容
  tutorialSidebar: [{type: 'autogenerated', dirName: 'MainDocs'}],

  // 2. 地图侧边栏：只包含 map 文件夹内容
  mapSidebar: [{type: 'autogenerated', dirName: 'map'}],
};

export default sidebars;
